name: sidescroller
description: "Desenvolvimento de jogo com flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0  # Compatible with Flutter 3.0.5
  logger: ^1.4.0  # Compatible with Flutter 3.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Use an older version of flutter_lints

flutter:
  uses-material-design: true